export const INDEX_PROXIES = [
  { symbol: "SPY", label: "S&P 500", kind: "etf" },
  { symbol: "QQQ", label: "Nasdaq 100", kind: "etf" },
  { symbol: "DIA", label: "Dow", kind: "etf" },
  { symbol: "IWM", label: "Russell 2000", kind: "etf" },
  { symbol: "^VIX", label: "VIX", kind: "index" },
  { symbol: "ES=F", label: "ES Futures", kind: "future" },
  { symbol: "NQ=F", label: "NQ Futures", kind: "future" },
  { symbol: "YM=F", label: "YM Futures", kind: "future" },
  { symbol: "RTY=F", label: "RTY Futures", kind: "future" },
] as const;

export const SECTOR_ETFS = [
  { symbol: "XLK", label: "Tech" },
  { symbol: "XLF", label: "Financials" },
  { symbol: "XLE", label: "Energy" },
  { symbol: "XLV", label: "Health" },
  { symbol: "XLI", label: "Industrial" },
  { symbol: "XLY", label: "Consumer Disc" },
  { symbol: "XLP", label: "Consumer Staples" },
  { symbol: "XLU", label: "Utilities" },
  { symbol: "XLB", label: "Materials" },
  { symbol: "XLRE", label: "Real Estate" },
  { symbol: "XLC", label: "Communication" },
] as const;

/** Liquid names used for free pre-earnings surveillance */
export const EARNINGS_WATCHLIST = [
  "AAPL",
  "MSFT",
  "NVDA",
  "AMZN",
  "GOOGL",
  "META",
  "TSLA",
  "AVGO",
  "AMD",
  "NFLX",
  "CRM",
  "ORCL",
  "ADBE",
  "INTC",
  "QCOM",
  "COST",
  "PEP",
  "KO",
  "JPM",
  "BAC",
  "GS",
  "MS",
  "V",
  "MA",
  "UNH",
  "LLY",
  "JNJ",
  "XOM",
  "CVX",
  "CAT",
  "BA",
  "DIS",
  "UBER",
  "SHOP",
  "PLTR",
  "COIN",
  "MSTR",
  "SMCI",
  "ARM",
  "MU",
];
